[package]
name = "binseq-bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
binseq = { git = "ssh://github.com/noamteyssier/binseq" }

[build-dependencies]
cbindgen = "0.28.0"

[lib]
name = "binseq"
crate-type = ["cdylib"]
